brand_aliases:
  爱肯拿:
    - Acana
    - acana
    - ACANA
  百利:
    - Instinct
    - instinct
    - 百利原始
    - 百利原始鸡
  法米娜:
    - Farmina
    - farmina
  金素:
    - Solid Gold
    - solidgold
  Halo:
    - halo
  金色交响乐: []
  小李子: []
  顽味:
    - 顽味鸡脖
    - 顽味青花鱼
  OP:
    - OP 三文鱼冻干
    - op
  MJamJam:
    - mjamjam
    - Mjamjam
  Arm & Hammer:
    - Arm and Hammer
    - 铁锤
